var WORLD_LOCATIONS=[
// Countries
'Afghanistan','Albania','Algeria','Andorra','Angola','Antigua and Barbuda','Argentina','Armenia','Australia','Austria',
'Azerbaijan','Bahamas','Bahrain','Bangladesh','Barbados','Belarus','Belgium','Belize','Benin','Bhutan',
'Bolivia','Bosnia and Herzegovina','Botswana','Brazil','Brunei','Bulgaria','Burkina Faso','Burundi','Cabo Verde','Cambodia',
'Cameroon','Canada','Central African Republic','Chad','Chile','China','Colombia','Comoros','Congo','Costa Rica',
'Croatia','Cuba','Cyprus','Czech Republic','Denmark','Djibouti','Dominica','Dominican Republic','Ecuador','Egypt',
'El Salvador','Equatorial Guinea','Eritrea','Estonia','Eswatini','Ethiopia','Fiji','Finland','France','Gabon',
'Gambia','Georgia','Germany','Ghana','Greece','Grenada','Guatemala','Guinea','Guinea-Bissau','Guyana',
'Haiti','Honduras','Hungary','Iceland','India','Indonesia','Iran','Iraq','Ireland','Israel',
'Italy','Jamaica','Japan','Jordan','Kazakhstan','Kenya','Kiribati','Kuwait','Kyrgyzstan','Laos',
'Latvia','Lebanon','Lesotho','Liberia','Libya','Liechtenstein','Lithuania','Luxembourg','Madagascar','Malawi',
'Malaysia','Maldives','Mali','Malta','Marshall Islands','Mauritania','Mauritius','Mexico','Micronesia','Moldova',
'Monaco','Mongolia','Montenegro','Morocco','Mozambique','Myanmar','Namibia','Nauru','Nepal','Netherlands',
'New Zealand','Nicaragua','Niger','Nigeria','North Korea','North Macedonia','Norway','Oman','Pakistan','Palau',
'Palestine','Panama','Papua New Guinea','Paraguay','Peru','Philippines','Poland','Portugal','Qatar','Romania',
'Russia','Rwanda','Saint Kitts and Nevis','Saint Lucia','Saint Vincent and the Grenadines','Samoa','San Marino',
'Sao Tome and Principe','Saudi Arabia','Senegal','Serbia','Seychelles','Sierra Leone','Singapore','Slovakia','Slovenia',
'Solomon Islands','Somalia','South Africa','South Korea','South Sudan','Spain','Sri Lanka','Sudan','Suriname','Sweden',
'Switzerland','Syria','Taiwan','Tajikistan','Tanzania','Thailand','Timor-Leste','Togo','Tonga','Trinidad and Tobago',
'Tunisia','Turkey','Turkmenistan','Tuvalu','Uganda','Ukraine','United Arab Emirates','United Kingdom','United States','Uruguay',
'Uzbekistan','Vanuatu','Vatican City','Venezuela','Vietnam','Yemen','Zambia','Zimbabwe',
// Major cities by region
// North America
'New York, US','Los Angeles, US','Chicago, US','Houston, US','Phoenix, US','Philadelphia, US','San Antonio, US','San Diego, US',
'Dallas, US','Austin, US','San Francisco, US','Seattle, US','Denver, US','Boston, US','Nashville, US','Miami, US',
'Atlanta, US','Las Vegas, US','Portland, US','Charlotte, US','Detroit, US','Minneapolis, US','Tampa, US','Orlando, US',
'Scottsdale, US','Raleigh, US','Salt Lake City, US','Washington DC, US','New Orleans, US','San Jose, US',
'Toronto, CA','Vancouver, CA','Montreal, CA','Calgary, CA','Ottawa, CA','Edmonton, CA',
'Mexico City, MX','Guadalajara, MX','Monterrey, MX','Cancun, MX',
// Europe
'London, UK','Manchester, UK','Birmingham, UK','Edinburgh, UK','Glasgow, UK',
'Paris, FR','Lyon, FR','Marseille, FR','Nice, FR',
'Berlin, DE','Munich, DE','Frankfurt, DE','Hamburg, DE',
'Madrid, ES','Barcelona, ES','Valencia, ES','Seville, ES',
'Rome, IT','Milan, IT','Florence, IT','Naples, IT',
'Amsterdam, NL','Rotterdam, NL','The Hague, NL',
'Brussels, BE','Antwerp, BE',
'Zurich, CH','Geneva, CH','Basel, CH',
'Vienna, AT','Salzburg, AT',
'Lisbon, PT','Porto, PT',
'Dublin, IE','Cork, IE',
'Stockholm, SE','Gothenburg, SE',
'Oslo, NO','Bergen, NO',
'Copenhagen, DK',
'Helsinki, FI',
'Warsaw, PL','Krakow, PL',
'Prague, CZ','Brno, CZ',
'Budapest, HU',
'Bucharest, RO',
'Athens, GR','Thessaloniki, GR',
'Istanbul, TR','Ankara, TR','Izmir, TR',
'Kyiv, UA','Lviv, UA',
'Moscow, RU','St. Petersburg, RU',
// Middle East
'Dubai, AE','Abu Dhabi, AE',
'Riyadh, SA','Jeddah, SA',
'Doha, QA',
'Kuwait City, KW',
'Manama, BH',
'Muscat, OM',
'Tel Aviv, IL','Jerusalem, IL',
'Amman, JO',
'Beirut, LB',
// Asia
'Tokyo, JP','Osaka, JP','Kyoto, JP',
'Seoul, KR','Busan, KR',
'Beijing, CN','Shanghai, CN','Shenzhen, CN','Hong Kong, CN','Guangzhou, CN',
'Taipei, TW',
'Singapore, SG',
'Bangkok, TH','Chiang Mai, TH',
'Kuala Lumpur, MY','Penang, MY',
'Jakarta, ID','Bali, ID',
'Manila, PH','Cebu, PH',
'Hanoi, VN','Ho Chi Minh City, VN',
'Mumbai, IN','Delhi, IN','Bangalore, IN','Hyderabad, IN','Chennai, IN',
'Karachi, PK','Lahore, PK','Islamabad, PK',
'Dhaka, BD',
'Colombo, LK',
'Kathmandu, NP',
// Africa
'Lagos, NG','Abuja, NG',
'Nairobi, KE','Mombasa, KE',
'Cape Town, ZA','Johannesburg, ZA','Durban, ZA',
'Cairo, EG','Alexandria, EG',
'Casablanca, MA','Marrakech, MA',
'Accra, GH',
'Addis Ababa, ET',
'Dar es Salaam, TZ',
'Kampala, UG',
'Kigali, RW',
'Dakar, SN',
'Tunis, TN',
'Algiers, DZ',
'Luanda, AO',
// South America
'Sao Paulo, BR','Rio de Janeiro, BR','Brasilia, BR',
'Buenos Aires, AR','Cordoba, AR',
'Santiago, CL',
'Lima, PE',
'Bogota, CO','Medellin, CO',
'Quito, EC','Guayaquil, EC',
'Caracas, VE',
'Montevideo, UY',
'Asuncion, PY',
'La Paz, BO',
// Oceania
'Sydney, AU','Melbourne, AU','Brisbane, AU','Perth, AU','Adelaide, AU',
'Auckland, NZ','Wellington, NZ',
// Caribbean & US Territories
'Puerto Rico','Guam','US Virgin Islands','American Samoa',
'San Juan, PR','Ponce, PR','Kingston, JM','Nassau, BS','Bridgetown, BB','Port of Spain, TT','Havana, CU','Santo Domingo, DO'
].sort();
